openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    This is a documentation of contacts app
tags:
  - name: Contacts
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://example.com/api/v1
paths:
  /auth/register:
    post:
      $ref: '../swagger/paths/contacts/auth/register_post.yaml'
  /auth/login:
    post:
      $ref: '../swagger/paths/contacts/auth/login_post.yaml'
  /auth/refresh:
    post:
      $ref: '../swagger/paths/contacts/auth/refresh_post.yaml'
  /auth/send-reset-email:
    post:
      $ref: '../swagger/paths/contacts/auth/send-reset-email_post.yaml'
  /auth/reset-pwd:
    post:
      $ref: '../swagger/paths/contacts/auth/reset-pwd_post.yaml'
  /auth/logout:
    post:
      $ref: '../swagger/paths/contacts/auth/logout_post.yaml'
  /contacts/{id}:
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
  /contacts:
    post:
      $ref: ../swagger/paths/contacts/post.yaml
    get:
      $ref: ../swagger/paths/contacts/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
